### ISSUE TITLE
Build as release generates error

### ISSUE THREAD

**Issue by sirconceptz** [nsNeruno/android_package_manager#13] opened 2023-12-20 15:33 UTC
When I trying to build project with implemented android_package_manager. Everything is okay in debug version, but in release version I getting the error like below:

> FAILURE: Build completed with 2 failures.
>
>1: Task failed with an exception.
>-----------
>* What went wrong:
>A problem occurred configuring project ':android_package_manager'.
>> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
>   > Namespace not specified. Specify a namespace in the module's build file. See >https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
>
>     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade >Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade->assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
>
>* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
>==============================================================================
>
>2: Task failed with an exception.
>-----------
>* What went wrong:
>Failed to query the value of property 'buildFlowServiceProperty'.
>> Could not isolate value >org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@34b86c9c of type >BuildFlowService.Parameters
>    A problem occurred configuring project ':android_package_manager'.
>       Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
>          Namespace not specified. Specify a namespace in the module's build file. See >https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
>
>           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade >Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade->assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
>
>* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
>==============================================================================
>
>BUILD FAILED in 1s
>Running Gradle task 'assembleRelease'...                         2 307ms
>Exception: Gradle task assembleRelease failed with exit code 1
>#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:491:9)
><asynchronous suspension>
>#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:220:5)
><asynchronous suspension>
>#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
><asynchronous suspension>
>#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:533:33)
><asynchronous suspension>
>#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
><asynchronous suspension>
>#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:745:27)
><asynchronous suspension>
>#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
><asynchronous suspension>
>#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
><asynchronous suspension>
>#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
><asynchronous suspension>
>#10     FlutterCommandRunner.runCommand.<anonymous closure> >(package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
><asynchronous suspension>
>#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
><asynchronous suspension>
>#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
><asynchronous suspension>
>#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
><asynchronous suspension>
>#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
><asynchronous suspension>
>#15     main (package:flutter_tools/executable.dart:90:3)
><asynchronous suspension>

**Comment by nsNeruno** [comment] 2024-01-10 16:26
Hi @sirconceptz 
I couldn't reproduce your issue, I have some released apps using this plugin and nothing went wrong on build.
My nearest guess is, you did upgrade your Gradle to `v8.x.x` or above which currently has issues with Flutter, unless you manually specifies namespaces under your project Gradle files. Take a look at this [reference](https://stackoverflow.com/questions/76108428/how-do-i-fix-namespace-not-specified-error-in-android-studio)

But to make sure, can you `gradle-wrapper.properties` under `android/gradle.wrapper` and `build.gradle` under `android`?

**Comment by nsNeruno** [comment] 2024-02-02 07:30
Closing this for now.

Requires more comprehensible proofs

**Closed by nsNeruno** 2024-02-02 07:30 UTC
